import os
from io import BytesIO
from typing import Optional

import edge_tts
from fastapi import FastAPI, HTTPException
from fastapi.responses import JSONResponse, Response
from gtts import gTTS
from pydantic import BaseModel, Field

app = FastAPI(title="FMN Edge TTS Service", version="1.0.0")

DEFAULT_VOICES = {
    "en": os.getenv("EDGE_TTS_DEFAULT_VOICE_EN", "en-US-JennyNeural"),
    "vi": os.getenv("EDGE_TTS_DEFAULT_VOICE_VI", "vi-VN-HoaiMyNeural"),
    "ja": os.getenv("EDGE_TTS_DEFAULT_VOICE_JA", "ja-JP-NanamiNeural"),
    "zh": os.getenv("EDGE_TTS_DEFAULT_VOICE_ZH", "zh-CN-XiaoxiaoNeural"),
    "ko": os.getenv("EDGE_TTS_DEFAULT_VOICE_KO", "ko-KR-SunHiNeural"),
}

ENABLE_GTTS_FALLBACK = os.getenv("EDGE_TTS_ENABLE_GTTS_FALLBACK", "true").strip().lower() in {
    "1",
    "true",
    "yes",
    "on",
}

GTTS_LANGUAGE_MAP = {
    "en": "en",
    "vi": "vi",
    "ja": "ja",
    "ko": "ko",
    "zh": "zh-CN",
}


class SynthesizeRequest(BaseModel):
    text: str = Field(min_length=1, max_length=5000)
    language_code: str = Field(min_length=2, max_length=10)
    voice: Optional[str] = None
    rate: str = "+0%"
    volume: str = "+0%"


def normalize_language_code(code: str) -> str:
    normalized = code.strip().lower()
    if "-" in normalized:
        normalized = normalized.split("-", 1)[0]

    aliases = {
        "vn": "vi",
        "jp": "ja",
        "kr": "ko",
        "cn": "zh",
    }

    return aliases.get(normalized, normalized)


def synthesize_with_gtts(text: str, language: str) -> bytes:
    gtts_language = GTTS_LANGUAGE_MAP.get(language)
    if not gtts_language:
        raise ValueError(f"gTTS fallback does not support language: {language}")

    buffer = BytesIO()
    tts = gTTS(text=text, lang=gtts_language)
    tts.write_to_fp(buffer)
    return buffer.getvalue()


@app.get("/health")
def health() -> JSONResponse:
    return JSONResponse({"status": "ok"})


@app.post("/synthesize")
async def synthesize(request: SynthesizeRequest) -> Response:
    language = normalize_language_code(request.language_code)
    voice = request.voice or DEFAULT_VOICES.get(language)
    if not voice:
        raise HTTPException(status_code=400, detail=f"Unsupported language: {request.language_code}")

    communicator = edge_tts.Communicate(
        text=request.text,
        voice=voice,
        rate=request.rate,
        volume=request.volume,
    )

    audio_data = bytearray()
    try:
        async for chunk in communicator.stream():
            if chunk.get("type") == "audio":
                audio_data.extend(chunk.get("data", b""))
    except Exception as edge_error:
        # Edge endpoint can occasionally reject websocket handshakes (403).
        if not ENABLE_GTTS_FALLBACK:
            raise HTTPException(status_code=502, detail=f"Edge TTS upstream error: {edge_error}") from edge_error

        try:
            fallback_bytes = synthesize_with_gtts(request.text, language)
            return Response(
                content=fallback_bytes,
                media_type="audio/mpeg",
                headers={
                    "x-tts-engine": "gtts",
                    "x-edge-fallback": "true",
                },
            )
        except Exception as gtts_error:
            raise HTTPException(
                status_code=502,
                detail=f"Edge TTS upstream error: {edge_error}; gTTS fallback failed: {gtts_error}",
            ) from gtts_error

    if len(audio_data) == 0:
        raise HTTPException(status_code=500, detail="No audio generated by Edge TTS")

    return Response(
        content=bytes(audio_data),
        media_type="audio/mpeg",
        headers={
            "x-tts-engine": "edge",
            "x-edge-voice": voice,
        },
    )
